SehirUygulamasi/Models/GezilecekSehirler.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SehirUygulamasi.Models
{
    public class GezilecekSehirler
    {
        public GezilecekSehirler()
        {
            CreatedDate = DateTime.Now;
        }
        public int Id { get; set; }

        [Required(ErrorMessage = "Please, enter a title for todo item")]
        [MaxLength(200)]

        public string Title { get; set; }

        [MaxLength(1500)]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [Display(Name = "Is Completed")]
        public bool IsCompleted { get; set; }

        [Display(Name = "Due Date")]
        public DateTime DueDate { get; set; }

        [ScaffoldColumn(false)]
        public DateTime CreatedDate { get; set; }

        [ScaffoldColumn(false)]
        public DateTime CompletedDate { get; set; }

        public int RemainingHour
        {
            get
            {
                var remaingTime = (DueDate - DateTime.Now);
                return (int)remaingTime.TotalHours;
            }
        }

        public int CategoryId { get; set; }

        public virtual Category Category { get; set; }
        
        public string CetUserId { get; set; }
        public virtual CetUser CetUser { get; set; }

        
    }
}

SehirUygulamasi/Controllers/GezilecekSehirlersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SehirUygulamasi.Data;
using SehirUygulamasi.Models;

namespace SehirUygulamasi.Controllers
{
    [Authorize]
    public class GezilecekSehirlersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<CetUser> _userManager;

        public GezilecekSehirlersController(ApplicationDbContext context, UserManager<CetUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
       
        // GET: GezilecekSehirlers
        public async Task<IActionResult> Index(SearchViewModel searchModel)
        {
            var cetUser = await _userManager.GetUserAsync(HttpContext.User);

            var query = _context.GezilecekSehirlers.Include(g => g.Category).Where(g=>g.CetUserId==cetUser.Id);
            if (!searchModel.ShowAll)
            {
                query = query.Where(g => !g.IsCompleted);
            }
            if (!String.IsNullOrWhiteSpace(searchModel.SearchText))
            {
                query = query.Where(g => g.Title.Contains(searchModel.SearchText)); 
            }

            query = query.OrderBy(g=>g.DueDate);
            searchModel.Result = await query.ToListAsync();

            return View(searchModel);
        }

        // GET: GezilecekSehirlers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gezilecekSehirler = await _context.GezilecekSehirlers
                .Include(g => g.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (gezilecekSehirler == null)
            {
                return NotFound();
            }

            return View(gezilecekSehirler);
        }

        // GET: GezilecekSehirlers/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewBag.CategorySelectList = new SelectList(_context.Categories, "Id", "Name");
            return View();
        }

        // POST: GezilecekSehirlers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,IsCompleted,DueDate,CategoryId")] GezilecekSehirler gezilecekSehirler)
        {
            var cetUser = await _userManager.GetUserAsync(HttpContext.User);
            gezilecekSehirler.CetUserId = cetUser.Id;
            if (ModelState.IsValid)
            {
                _context.Add(gezilecekSehirler);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", gezilecekSehirler.CategoryId);
            return View(gezilecekSehirler);
        }

        // GET: GezilecekSehirlers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gezilecekSehirler = await _context.GezilecekSehirlers.FindAsync(id);

            
            var currentUser = await _userManager.GetUserAsync(HttpContext.User);
            if (gezilecekSehirler.CetUserId != currentUser.Id)
            {
                return Unauthorized();
            }
            if (gezilecekSehirler == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", gezilecekSehirler.CategoryId);
            return View(gezilecekSehirler);
        }

        // POST: GezilecekSehirlers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,IsCompleted,DueDate,CategoryId,CreatedDate,CetUserId")] GezilecekSehirler gezilecekSehirler)
        {
            if (id != gezilecekSehirler.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var oldTodo = await _context.GezilecekSehirlers.FindAsync(id);
                    var currentUser = await _userManager.GetUserAsync(HttpContext.User);
                    if (oldTodo.CetUserId != currentUser.Id)
                    {
                        return Unauthorized();
                    }
                    oldTodo.Title = gezilecekSehirler.Title;
                    oldTodo.CompletedDate = gezilecekSehirler.CompletedDate;
                    oldTodo.CategoryId = gezilecekSehirler.CategoryId;
                    oldTodo.IsCompleted = gezilecekSehirler.IsCompleted;
                    oldTodo.Description = gezilecekSehirler.Description;
                    oldTodo.DueDate = gezilecekSehirler.DueDate;

                    _context.Update(oldTodo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GezilecekSehirlerExists(gezilecekSehirler.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", gezilecekSehirler.CategoryId);
            return View(gezilecekSehirler);
        }

        // GET: GezilecekSehirlers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gezilecekSehirler = await _context.GezilecekSehirlers
                .Include(g => g.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (gezilecekSehirler == null)
            {
                return NotFound();
            }

            return View(gezilecekSehirler);
        }

        // POST: GezilecekSehirlers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gezilecekSehirler = await _context.GezilecekSehirlers.FindAsync(id);
            _context.GezilecekSehirlers.Remove(gezilecekSehirler);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> MakeComplete(int id, bool showAll)
        {
            return await ChangeStatus(id, true, showAll);

        }

        public async Task<IActionResult> MakeInComplete(int id, bool showAll)
        {
            return await ChangeStatus(id, false, showAll);

        }

        private async Task<IActionResult> ChangeStatus(int id, bool status, bool currentShowallValue)
        {
            var sehirItemItem = _context.GezilecekSehirlers.FirstOrDefault(x => x.Id == id);
            if (sehirItemItem == null)
            {
                return NotFound();
            }
            sehirItemItem.IsCompleted = status;
            sehirItemItem.CompletedDate = DateTime.Now;

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { showall = currentShowallValue });
        }


        private bool GezilecekSehirlerExists(int id)
        {
            return _context.GezilecekSehirlers.Any(e => e.Id == id);
        }
    }
}

SehirUygulamasi/Views/GezilecekSehirlers/Create.cshtml
@model SehirUygulamasi.Models.GezilecekSehirler

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>GezilecekSehirler</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsCompleted" /> @Html.DisplayNameFor(model => model.IsCompleted)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class ="form-control" asp-items="ViewBag.CategorySelectList"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SehirUygulamasi/Views/GezilecekSehirlers/Delete.cshtml
@model SehirUygulamasi.Models.GezilecekSehirler

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GezilecekSehirler</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsCompleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsCompleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DueDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SehirUygulamasi/Views/GezilecekSehirlers/Details.cshtml
@model SehirUygulamasi.Models.GezilecekSehirler

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>GezilecekSehirler</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsCompleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsCompleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DueDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SehirUygulamasi/Views/GezilecekSehirlers/Edit.cshtml
@model SehirUygulamasi.Models.GezilecekSehirler

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>GezilecekSehirler</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsCompleted" /> @Html.DisplayNameFor(model => model.IsCompleted)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">

                <input asp-for="CreatedDate" type="hidden" class="form-control" />
                <input asp-for="CetUserId" type="hidden" class="form-control" />
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SehirUygulamasi/Views/GezilecekSehirlers/Index.cshtml
@model SearchViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Gezilecek Sehirler</h1>

<p>
    <a asp-action="Create">Gezmek istediğin bir şehir ekle</a>
</p>

<p>
    @if (Model.ShowAll)
    {
        <a asp-action="Index" asp-route-showall="false">Sadece Gidilmemişleri Göster</a>
    }
    else
    {
        <a asp-action="Index" asp-route-showall="true">Hepsini Göster</a>
    }

</p>

<form asp-action="Index" asp-controller="GezilecekSehirlers" method="get">

    <div class="form-group">
        <label asp-for="SearchText" class="control-label"></label>
        <input asp-for="SearchText" class="form-control" />

    </div>
    <div class="form-group">
        <label asp-for="ShowAll" class="control-label"></label>
        <input asp-for="ShowAll" class="form-control" />

    </div>
    <div class="form-group">
        <input type="submit" value="Search" class="btn btn-primary" />
    </div>



</form>

<table class="table">
    <thead>
        <tr>
            <th>
               Title
            </th>
            <th>
                Category
            </th>
            
            <th>
               DueDate
            </th>
            <th>
                RemainingHour
            </th>
            <th>
               IsCompleted
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Result) {
        <tr>
            <td>
                @if (item.IsCompleted)
                {
                    <del> @Html.DisplayFor(modelItem => item.Title) </del>

                }
                else
                {
                    @Html.DisplayFor(modelItem => item.Title)
                }

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DueDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RemainingHour)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsCompleted)
            </td>


            <td>

                @if (item.IsCompleted)
                {
                    <a asp-action="MakeInComplete" asp-route-id="@item.Id" asp-route-showAll="@Model.ShowAll">Gidilmemiş</a>
                }
                else
                {
                    <a asp-action="MakeComplete" asp-route-id="@item.Id"asp-route-showAll="@Model.ShowAll">Gidilmiş</a>
                }

                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>